<?php
// This is a SPIP language file  --  Ceci est un fichier langue de SPIP
// extrait automatiquement de https://trad.spip.net/tradlang_module/geol?lang_cible=en
// ** ne pas modifier le fichier **

if (!defined('_ECRIRE_INC_VERSION')) {
	return;
}

$GLOBALS[$GLOBALS['idx_lang']] = array(

	// A
	'afficher' => 'Show',
	'afficher_par_page' => 'per page',
	'aide' => 'Help',
	'amis_accepter_demande' => 'Accept request',
	'amis_ajouter' => 'Add to my contacts',
	'amis_aucun' => '0 contact',
	'amis_demandes' => 'Requests',
	'amis_nb' => 'Contacts',
	'amis_nb_demandes' => '@nb@ new requests',
	'amis_nb_un' => 'Contact',
	'amis_titre' => 'Contacts',
	'amis_titre_auteur' => '@nom@’s contacts',
	'amis_une_demande' => '1 new request',
	'amis_voir_tous' => 'Show all contacts',
	'annuler' => 'Cancel',
	'auteur_carte' => 'Show contributions on a map', # RELIRE

	// C
	'carte' => 'Map',
	'categories' => 'Categories',
	'categories_scientifiques' => 'Scientific categories',
	'cfg_descr_geol' => 'Géodiversité configuration',
	'cfg_explication_nom_fichier_kml' => 'Change the name of the KML file generated by the site  (without extension).',
	'cfg_explication_zoom_minicartes' => 'Zoom level to use for static maps in navigation column of the site.',
	'cfg_label_couleur_primaire' => 'Primary color',
	'cfg_label_groupe_echelle' => 'Keyword group for scale',
	'cfg_label_groupe_tags' => 'Keyword group for tags',
	'cfg_label_nom_fichier_kml' => 'KML File',
	'cfg_label_secteur_categories' => 'Section for categories',
	'cfg_label_secteur_medias' => 'Section for medias',
	'cfg_label_zoom_minicartes' => 'Maps zoom',
	'cfg_titre_geol' => 'Géodiversité',
	'commentaire' => '@nb@ comment',
	'commentaire_aucun' => 'No comment',
	'commentaire_zero' => '0 comment',
	'commentaires' => '@nb@ comments',
	'commentaires_a_date_heure' => 'at',
	'commentaires_le_date_jour' => 'On',
	'commentaires_permalink_pour' => 'Permanent link to',
	'commentaires_titre' => 'Your comments',
	'commenter' => 'Comment',
	'contact_auteur' => 'Contact @nom@',
	'contrib' => 'Contribution',
	'contrib_0' => 'No contribution to date',
	'contrib_auteur' => '1 contribution to date',
	'contribs' => 'Contributions',
	'contribs_auteur' => '@nb@ contributions to date',
	'contribuer' => 'Contribute',
	'contributeur' => '1 author overall',
	'contributeurs' => '@nb@ authors overall',
	'contributeurs_admins' => 'Administrators',
	'contributeurs_les' => 'Authors',
	'contributeurs_nouveaux' => 'Last registred',
	'couches_kml' => 'Overlays',
	'creer_compte' => 'Sign up',
	'creer_profil' => 'Create your account',

	// D
	'date_le' => 'on',
	'de' => 'By',
	'deplie_replie' => 'Fold/Unfold',
	'depuis_page' => 'From page', # RELIRE
	'dernieres_contribs' => 'Recent contributions',
	'description' => 'Description',
	'doc_modifier' => 'Modify document',
	'doc_supprimer' => 'Delete document',
	'doc_supprimer_confirm' => 'Are you sure you want to delete this document?',
	'doc_telecharger' => 'Download document',
	'documents_annexes' => 'Additional documents',

	// E
	'echelle_media' => 'Subject’s scale',
	'envoye_le' => 'Posted on:',
	'evaluation_contenu' => 'Content evaluation',
	'explication_article_prepa' => '1 document pending publication.',
	'explication_inscription' => 'Enter your name and email address into the form below to receive your login.',
	'explication_liste_admins' => 'These authors are directors or members of the scientific community. You can contact them if you want to join this group to take part in indexing the media.',
	'explication_recherche_filtree' => 'The search results are filtered according to the criteria shown below. You can disable each of these criteria by clicking on it.',
	'explication_select_multiple' => 'Use the CTRL key on your keyboard to (de) select multiple items.',
	'explication_suivi_auteur' => 'Follow the author’s contributions on the RSS (rss feed). Export his contribution map to another mapping tool.',
	'explication_suivi_categorie' => 'Follow the category contributions of the RSS feed. Export the map of the contributions to another mapping tool.',
	'explication_suivi_mot' => 'Follow the tag contributions on the RSS feed. Export the contribution map to another mapping tool.',
	'exporter_coordonnees' => 'Export location: GPS, KML',

	// F
	'fans' => 'Fans',
	'favoris' => 'Favorites',
	'favoris_nb_personne' => '1 author added this document to his favorites',
	'favoris_nb_personnes' => '@nb@ authors added this document to their favorites',
	'favoris_retirer' => 'Remove from favorites',
	'favoris_voir_tous' => 'Show all favorites',
	'flux_georss' => 'GeoRSS Feed',
	'flux_kml' => 'KML Feed',
	'flux_rss' => 'RSS Feed',

	// G
	'galerie' => 'Gallery',

	// I
	'info_embed_carte' => 'Embed the map on your website',
	'info_vide' => 'not specified',
	'info_vide_f' => 'not specified',
	'inscription' => 'Sign up',
	'inscrit_le' => 'Registred on',

	// L
	'legend_editer_profil' => 'Edit your profile',
	'licence_media' => 'Document license', # RELIRE
	'lien_grande_carte' => 'Show on a bigger map', # verif RELIRE
	'localisation' => 'Location',

	// M
	'media_non_geolocalise' => 'Document is not located', # verif RELIRE
	'media_type' => 'Document type',
	'media_type_audios' => 'Sounds',
	'media_type_images' => 'Images',
	'media_type_textes' => 'KML, KMZ, PDF files',
	'media_type_videos' => 'Videos',
	'message_article_publie_prepa' => 'You have to publish your document before uploading a new one.', # RELIRE
	'modifier' => 'Edit',
	'modifier_carte' => 'Edit location',
	'modifier_categories' => 'Edit categories',
	'modifier_echelle' => 'Edit scale',
	'modifier_licence' => 'Edit licence',
	'modifier_pass' => 'Change your password',
	'mon_espace' => 'My space',
	'mot_doux_categories' => 'You have to member of the scientific commity to add a scientific keyword.', # verif RELIRE
	'mot_doux_premier_upload' => 'This is the first time you publish a media, <a href="@url@">see the online help</a>.', # verif RELIRE

	// N
	'nav_a_propos' => 'About',
	'nav_accueil' => 'Home',
	'nav_aide' => 'Help',
	'nav_aide_faq' => 'Help, F.A.Q on the wiki',
	'nav_blog' => 'Blog',
	'nav_explorer' => 'Explore',
	'nav_twitter' => 'Twitter',
	'nav_univers' => 'Universe',
	'nav_wiki' => 'Wiki',
	'note_ajouter' => 'Add a caption',

	// O
	'objets_auteurs' => 'authors',
	'objets_medias' => 'medias',

	// P
	'partage_socialtags' => 'Share this',
	'partage_telechargement' => 'Download / Share',
	'pas_description' => 'No description yet.',
	'pied_vous' => 'You',
	'profil' => 'Account',
	'profil_bio' => 'Bio',
	'profil_mail' => 'e-mail adress',
	'profil_nom' => 'Name or alias',
	'profil_openid' => 'OpenID',
	'profil_url' => 'Site’s URL',
	'publie_le' => 'Posted on',
	'publie_par' => 'Posted by',
	'publier' => 'Publish',
	'publier_media' => 'Publish a document',
	'publier_nouveau_media' => 'Publish a new document',
	'publier_prepa_media' => '1 document pending publication.', # RELIRE

	// R
	'recherche_avancee' => 'Advanced search',
	'recherche_libre' => 'Text search',
	'recherche_options' => 'Search options',
	'recherche_retirer_filtre' => 'Remove filter',
	'rechercher' => 'Search',
	'retour_page_media' => 'Back to document page',

	// S
	'signaler_bug' => 'Create a bug report',
	'signaler_erreur_localisation' => 'Report location error', # RELIRE
	'site_spip' => 'Made with SPIP',
	'statut_admin' => 'Admin',
	'statut_admin_restreint' => 'Restricted admin',
	'statut_auteur' => 'Status',
	'suivi_edito' => 'Editorial monitoring', # RELIRE
	'suivi_edito_filtre_categorie' => 'Contributions without categorie',
	'suivi_edito_filtre_texte' => 'Contributions without description',
	'suivi_edito_filtres' => 'Contributions types',
	'sujet_erreur_localisation' => 'location error',
	'syndic' => 'Syndication',

	// T
	'tag_docs_publics' => 'See all public documents tagged with @titre@.', # RELIRE
	'tags' => 'Tags',
	'tags_auteurs' => 'Autor’s tags',
	'tags_modifier' => 'Edit tags',
	'tags_tous' => 'All the tags',
	'tags_utilises_par' => 'Tags used by @nom@',
	'toutes' => 'All',
	'trier' => 'Sort:',
	'trier_par_date' => 'by date',
	'trier_par_date_inscription' => 'by registred date',
	'trier_par_nom' => 'by name',
	'trier_par_points' => 'by revelancy',
	'trier_par_pop' => 'by popularity',

	// V
	'visite' => '1 visit',
	'visite_0' => '0 visit',
	'visites' => '@nb@ visits',
	'vue' => '1 view',
	'vues' => '@nb@ views',

	// Z
	'zoom' => 'Zoom'
);
